#!/bin/bash

# -e ferma exec quando c'e' un errore
# -u (nounset) considera unset env-var come errori
# -o pipefail restituisce ultimo exit code di errore
set -euo pipefail

# Le migrazioni vanno fatte in locale, nel pod sono applicate e basta
echo "⚙️ Applying migration"
python main.py db upgrade heads

APP=main:app
echo "🌐 Running in environment: ${ENVIRONMENT^^} -- Testing: $TESTING"

echo "🚀 Ready to launch the main process..."
if (( $# > 0 )); then
    exec "$0"
fi

if [ "$ENVIRONMENT" == "tilt" ] || [ "$ENVIRONMENT" == "dev" ]; then
    HOSTNAME="0.0.0.0"
    exec uvicorn \
        --reload \
        --workers 4 \
        --host "$HOSTNAME" \
        --port 8080 \
        $APP
else
    exec uvicorn \
        --workers 4 \
        --host "$HOSTNAME" \
        --port 8080 \
        $APP
fi